In [1]:
import numpy as np
import random

# Grid dimensions
grid_size = 4

# Define actions: 0=up, 1=down, 2=left, 3=right
actions = [0, 1, 2, 3]

# Hyperparameters
alpha = 0.1   # Learning rate
gamma = 0.9   # Discount factor
epsilon = 0.2 # Exploration rate
num_episodes = 1000

# Initialize Q-table with zeros: dimensions [rows, cols, actions]
Q = np.zeros((grid_size, grid_size, len(actions)))

def choose_action(state):
    """Choose an action using the epsilon-greedy policy."""
    if random.uniform(0, 1) < epsilon:
        return random.choice(actions)
    else:
        row, col = state
        return np.argmax(Q[row, col])

def step(state, action):
    """Take an action and return the new state, reward, and whether the episode is done."""
    row, col = state
    # Determine new state based on action
    if action == 0:   # up
        new_row = max(row - 1, 0)
        new_col = col
    elif action == 1: # down
        new_row = min(row + 1, grid_size - 1)
        new_col = col
    elif action == 2: # left
        new_row = row
        new_col = max(col - 1, 0)
    elif action == 3: # right
        new_row = row
        new_col = min(col + 1, grid_size - 1)
    
    new_state = (new_row, new_col)
    
    # Check if the agent has reached the goal
    if new_state == (grid_size - 1, grid_size - 1):
        reward = 10
        done = True
    else:
        reward = -1
        done = False
    return new_state, reward, done

# Q-learning algorithm
for episode in range(num_episodes):
    state = (0, 0)  # Start at the top-left corner
    done = False
    while not done:
        action = choose_action(state)
        new_state, reward, done = step(state, action)
        
        row, col = state
        new_row, new_col = new_state
        best_next_action = np.argmax(Q[new_row, new_col])
        
        # Q-learning update rule
        Q[row, col, action] = Q[row, col, action] + alpha * (
            reward + gamma * Q[new_row, new_col, best_next_action] - Q[row, col, action]
        )
        
        state = new_state

print("Trained Q-table:")
print(Q)

Trained Q-table:
[[[ 0.61189759  1.8098      0.62177342  1.78638937]
  [-0.34651609  0.45426068 -0.56022915  3.12183445]
  [ 1.58851119  4.5799986   0.16529857  1.66663855]
  [-0.48136681  5.22610408  0.34273198 -0.4900995 ]]

 [[ 0.61091015  3.04353009  1.78134331  3.122     ]
  [ 1.77441617  4.54160191  1.72808821  4.58      ]
  [ 3.07901913  6.2         3.10644938  6.15904689]
  [ 0.88648166  7.99999496  1.97185305  4.23876558]]

 [[-0.52016824 -0.81555943  0.75116503  4.56975313]
  [ 1.93177964  1.48844227  1.62459942  6.19999955]
  [ 4.55920401  7.93418707  4.57367764  8.        ]
  [ 6.1946142  10.          6.18545109  7.96659612]]

 [[-0.52804572 -0.4900995  -0.4900995   1.12486757]
  [ 0.27889931  0.57910859 -0.25154735  6.63345855]
  [ 2.479913    2.99720348  1.54721521  9.99373421]
  [ 0.          0.          0.          0.        ]]]


In [2]:
def get_best_path(Q):
    state = (0, 0)
    path = [state]
    # A safeguard to avoid infinite loops (if something goes wrong)
    max_steps = grid_size * grid_size
    steps = 0
    while state != (grid_size - 1, grid_size - 1) and steps < max_steps:
        row, col = state
        # Choose the best action according to the learned Q-values
        action = np.argmax(Q[row, col])
        state, reward, done = step(state, action)
        path.append(state)
        steps += 1
    return path

# After training, retrieve and print the optimal path
best_path = get_best_path(Q)
print("Best (fastest) path to the goal:")
print(best_path)

Best (fastest) path to the goal:
[(0, 0), (1, 0), (1, 1), (1, 2), (2, 2), (2, 3), (3, 3)]
